### ISSUE TITLE
NITRC CE AMIs

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#353]
niceman create invocation demonstrating instantiating nitrc ce in Amazon

**Comment by mjtravers** [comment]
@yarikoptic 
Here is a code snippet for creating a NITRC-CE EC2 instance with niceman:

```
niceman create my-nitrc-ce -t aws-ec2 -b \
access_key_id=YOUR_AWS_ACCESS_KEY_ID \
secret_access_key=YOUR_AWS_SECRET_ACCESS_KEY \
region_name=us-east-1 \
instance_type=t2.medium \
key_name=YOUR_AWS_KEY_PAIR_NAME \
key_filename=YOUR_LOCAL_PRIVATE_KEY_PATH \
image=ami-0f536567844fb9576
```

It works, however, the "niceman login my-nitrc-ce" only works if the AWS access_key_id and secret_access_key are saved to the niceman.cfg file, like so:

```
[aws-ec2]
access_key_id = MY_ACCESS_KEY_ID
secret_access_key = MY_SECRET_ACCESS_KEY
```

This affects all the commands: login, stop, delete, etc. Is this okay? Or do we want to add the niceman "-b" option we have for the create command to all of the commands? Or would it be better to simply prompt the user when connecting to AWS for the access_keys and offer to save them to the niceman.cfg file for them so they aren't prompted every time? If we prompt to save, we could rather save to the inventory.yml file so that different EC2 instances could be at different AWS subscriptions.

Not sure what our security best practices are for storing the access keys. Thoughts?

**Comment by yarikoptic** [comment]
I believe @kyleam fixed up this issue yesterday in https://github.com/ReproNim/niceman/pull/354 so we just need to have that `[aws-ec2]` section in niceman.cfg and then not list them in cmdline.  And it seems to work -- only that config section is `aws` not `aws-ec2` (since those are generic for aws).

Regarding the ssh keys (#298) I still think that ideally we shouldn't burden user with that.  May be we could/should create a key per each resource name, and remove when we remove that resource.  Then cmdline invocation simplifies to

```shell
niceman create my-nitrc-ce -t aws-ec2 -b region_name=us-east-1 instance_type=t2.medium image=ami-0f536567844fb9576
```
and taking it further - initiated https://github.com/ReproNim/niceman/issues/356

**Comment by yarikoptic** [comment]
and I verified that the one you provided has datalad and probably is the NITRC one (nothing in the environment like NITRC_CE_VERSION variable) hinted me that it is  . thus closing

**Comment by mjtravers** [comment]
Okay, that sounds good.

On NITRC-CE, we have a motd display at login. We have been discussing adding a env variable but nothing in there yet.

**Comment by yarikoptic** [comment]
> On NITRC-CE, we have a motd display at login.

FWIW
```shell
$> niceman login my-nitrc-ce
ubuntu:~$ 
```
probably because I have `~/.hushlogin` locally? ;)

**Comment by mjtravers** [comment]
Ha. That is diabolical.

**Comment by kyleam** [comment]
> probably because I have `~/.hushlogin` locally? ;)

I also don't see a display at login (no .hushlogin).

**Comment by kyleam** [comment]
> I also don't see a display at login (no .hushlogin).

And if I log in with `ssh -i <key> <user>@<ec2_instance.public_ip_address>` I do see the "Welcome to the NITRC Computation Environment [...]" banner.
